import type { TokenType } from '../../lang/token/token-type.js';

export const KEYWORDS: Record<string, TokenType> = {
    fn:       'FN',
    let:      'LET',
    mut:      'MUT',
    struct:   'STRUCT',
    enum:     'ENUM',
    impl:     'IMPL',
    trait:    'TRAIT',
    for:      'FOR',
    in:       'IN',
    while:    'WHILE',
    loop:     'LOOP',
    if:       'IF',
    else:     'ELSE',
    match:    'MATCH',
    return:   'RETURN',
    break:    'BREAK',
    continue: 'CONTINUE',
    self:     'SELF',
    pub:      'PUB',
    true:     'TRUE',
    false:    'FALSE',
    Some:     'SOME',
    None:     'NONE',
    Ok:       'OK',
    Err:      'ERR',
    // Type keywords
    f64:      'F64',
    i64:      'I64',
    bool:     'BOOL_TY',
    str:      'STR_TY',
    color:    'COLOR_TY',
    series:   'SERIES_TY',
    Option:   'OPTION_TY',
    Result:   'RESULT_TY',
    void:     'VOID_TY',
};
